apiVersion: v1
kind: Service
metadata:
  name: k8s-manager
  namespace: kube-system
  labels:
    app: k8s-manager
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: k8s-manager