apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-manager-v1
  namespace: kube-system
  labels:
    k8s-app: k8s-manager
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: k8s-manager
    version: v1
  template:
    metadata:
      labels:
        k8s-app: k8s-manager
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: mlamina/k8s-manager:latest
          name: k8s-manager
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 80
              name: http