apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-manager
  namespace: kube-system
  labels:
    app: k8s-manager
spec:
  replicas: 1
  selector:
    app: k8s-manager
  template:
    metadata:
      labels:
        app: k8s-manager
    spec:
      containers:
        - image: mlamina/k8s-manager:latest
          name: k8s-manager
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          ports:
            - containerPort: 80
              name: http