apiVersion: v1
kind: Service
metadata:
  name: k8s-manager
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "K8sManager"
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    k8s-app: k8s-manager